ISP_FW_VER=2.2.0

SRCS := $(DIR)/tx-isp-funcs.c \
	$(DIR)/tx-isp-module.c \
	$(KERNEL_VERSION)/isp/common/tx-isp-sinfo.c

KVERSION := 4-4-94

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += $(KERNEL_VERSION)/sdk/$(SOC_FAMILY)/$(ISP_FW_VER)/lib$(SOC_FAMILY)-firmware-$(KVERSION).a

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
